on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build and Deploy"
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'
      - name: Get Flutter Packages
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Deploy
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
       